# Generated by Django 4.2.9 on 2024-01-05 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0009_profile_remove_danismanprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profil_onaylama',
            new_name='is_profile_approved',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='belge_upload',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='edu',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='uzmanlik_alani',
        ),
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expertise_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
