# Generated by Django 4.2.9 on 2024-01-05 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0010_rename_profil_onaylama_profile_is_profile_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_profile_approved',
            new_name='profil_onay_durumu',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='expertise_area',
            new_name='uzmanlik_alani',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='document',
        ),
        migrations.AddField(
            model_name='profile',
            name='belge_yukle',
            field=models.ImageField(blank=True, null=True, upload_to='belge/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
