# Generated by Django 4.2.9 on 2024-01-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='belge_yukle',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ('College', 'College'), ('Graduate School', 'Graduate School')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uzmanlik_alani',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
