# Generated by Django 4.2.9 on 2024-01-06 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, choices=[('High School', 'High School'), ('College', 'College'), ('Graduate School', 'Graduate School')], max_length=50, null=True)),
                ('belge_yukle', models.FileField(blank=True, max_length=50, null=True, upload_to='files/')),
                ('uzmanlik_alani', models.CharField(blank=True, max_length=50, null=True)),
                ('profil_onay_durumu', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
