# Generated by Django 4.2.9 on 2024-01-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_clientprofile_belge_yukle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
