# Generated by Django 4.2.9 on 2024-03-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counselor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalismaGunu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('baslangic_saati', models.TimeField()),
                ('bitis_saati', models.TimeField()),
                ('seans_suresi', models.IntegerField(help_text='Dakika cinsinden seans süresi')),
                ('ara_suresi', models.IntegerField(help_text='Dakika cinsinden ara süresi')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calisma_gunu_araliklari', to='counselor.consultantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calisma_gunu', models.DateField()),
                ('baslangic_saati', models.TimeField()),
                ('bitis_saati', models.TimeField()),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='counselor.consultantprofile')),
            ],
        ),
    ]
