# Generated by Django 4.2.9 on 2024-03-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counselor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount rate in percentage', max_digits=5)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='counselor.consultantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sold', 'Sold')], default='Pending', max_length=50)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='counselor.consultantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_duration', models.IntegerField(help_text='Session duration in minutes')),
                ('break_duration', models.IntegerField(help_text='Break duration in minutes')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_day', to='counselor.consultantprofile')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_day', to='appointment.price')),
            ],
            options={
                'unique_together': {('counselor', 'start_date', 'end_date', 'start_time', 'end_time')},
            },
        ),
    ]
