# Generated by Django 4.2.9 on 2024-03-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0001_initial'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_duration', models.IntegerField(help_text='Session duration in minutes')),
                ('break_duration', models.IntegerField(help_text='Break duration in minutes')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_day_ranges', to='counselor.consultantprofile')),
            ],
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='baslangic_saati',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='bitis_saati',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='calisma_gunu',
            new_name='work_day',
        ),
        migrations.DeleteModel(
            name='CalismaGunu',
        ),
    ]
