# Generated by Django 4.2.9 on 2024-03-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('appointment', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('client', 'appointment')},
        ),
    ]
