# Generated by Django 4.2.9 on 2024-02-29 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalismaGunu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_gunu', models.DateField()),
                ('bitis_gunu', models.DateField()),
                ('baslangic_saati', models.TimeField()),
                ('bitis_saati', models.TimeField()),
                ('seans_suresi', models.IntegerField(help_text='Dakika cinsinden seans süresi')),
                ('ara_suresi', models.IntegerField(help_text='Dakika cinsinden ara süresi')),
            ],
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_saati', models.TimeField()),
                ('bitis_saati', models.TimeField()),
                ('calisma_gunu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='tests.calismagunu')),
            ],
        ),
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calismagunu',
            name='doktor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calisma_gunleri', to='tests.doktor'),
        ),
    ]
