# Generated by Django 4.2.9 on 2024-03-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='doktor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='tests.doktor'),
            preserve_default=False,
        ),
    ]
