# Generated by Django 4.2.9 on 2024-02-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calismagunu',
            old_name='baslangic_gunu',
            new_name='gun',
        ),
        migrations.RemoveField(
            model_name='calismagunu',
            name='bitis_gunu',
        ),
    ]
