# Generated by Django 4.2.9 on 2024-01-05 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0008_danisanprofile_danismanprofile_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('edu', models.CharField(blank=True, max_length=100, null=True)),
                ('lang', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('belge_upload', models.FileField(blank=True, null=True, upload_to='belge/')),
                ('uzmanlik_alani', models.CharField(blank=True, max_length=100, null=True)),
                ('profil_onaylama', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='danismanprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='DanisanProfile',
        ),
        migrations.DeleteModel(
            name='DanismanProfile',
        ),
    ]
