# Generated by Django 4.2.9 on 2024-01-05 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0011_rename_is_profile_approved_profile_profil_onay_durumu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('18-25', '18-25'), ('26-35', '26-35')], max_length=10)),
                ('location', models.CharField(choices=[('Istanbul', 'Istanbul'), ('Ankara', 'Ankara')], max_length=50)),
                ('education', models.CharField(choices=[('High School', 'High School'), ('College', 'College')], max_length=50)),
                ('belge_yukle', models.CharField(blank=True, choices=[('Belge1', 'Belge1'), ('Belge2', 'Belge2')], max_length=50, null=True)),
                ('uzmanlik_alani', models.CharField(blank=True, choices=[('Uzmanlık1', 'Uzmanlık1'), ('Uzmanlık2', 'Uzmanlık2')], max_length=50, null=True)),
                ('profil_onay_durumu', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
